version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data